### ISSUE TITLE
Setup "Stale" GitHub application

### ISSUE THREAD

**Issue by atc0005** [atc0005/elbow#153]
## Overview

> Automatically close stale Issues and Pull Requests that tend to accumulate during a project.
> 
> After a period of inactivity, a label will be applied to mark an issue as stale, and optionally post a comment to notify contributors that the Issue or Pull Request will be closed.
> 
> If the Issue or Pull Request is updated, or anyone comments, then the stale label is removed.
> 
> If no more activity occurs, the Issue or Pull Request will be automatically closed with an optional comment.

## Pricing and setup

- Price: $0

### Installation

> After installing the app, create `.github/stale.yml` in the default branch to enable it:
> 
> ```yaml
> # Number of days of inactivity before an issue becomes stale
> daysUntilStale: 60
> # Number of days of inactivity before a stale issue is closed
> daysUntilClose: 7
> # Issues with these labels will never be considered stale
> exemptLabels:
>   - pinned
>   - security
> # Label to use when marking an issue as stale
> staleLabel: wontfix
> # Comment to post when marking an issue as stale. Set to `false` to disable
> markComment: >
>   This issue has been automatically marked as stale because it has not had
>   recent activity. It will be closed if no further activity occurs. Thank you
>   for your contributions.
> # Comment to post when closing a stale issue. Set to `false` to disable
> closeComment: false
> ```
> 

## References

- https://github.com/marketplace/stale

**Comment by atc0005** [comment]
Example here:

https://github.com/go-gitea/gitea/blob/master/.github/stale.yml

```yaml
# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 60

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 14

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - status/blocked 
  - kind/security 
  - lgtm/done
  - reviewed/confirmed
  - priority/critical
  - kind/proposal

# Set to true to ignore issues in a project (defaults to false)
exemptProjects: false

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: false

# Label to use when marking as stale
staleLabel: stale

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs during the next 2 weeks. Thank you
  for your contributions.

# Comment to post when closing a stale Issue or Pull Request.
closeComment: >
  This issue has been automatically closed because of inactivity.
  You can re-open it if needed.

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 1

# Optionally, specify configuration settings that are specific to just 'issues' or 'pulls':
pulls:
  daysUntilStale: 60
  daysUntilClose: 60
  markComment: >
    This pull request has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs during the next 2 months. Thank you
    for your contributions.
  closeComment: >
    This pull request has been automatically closed because of inactivity.
    You can re-open it if needed.

```
