### ISSUE TITLE
Use mfridman/tparse package to analyze test output

### ISSUE THREAD

**Issue by atc0005** [atc0005/elbow#162]
https://github.com/mfridman/tparse

One for *way* down the line once I've learned how to implement proper testing for the codebase. Figured it was worth noting now.

**Comment by atc0005** [comment]
Example usage:

https://github.com/psampaz/gothanks/blob/dc2fc7cb2e27c5022f0ba1cea332355819b5d1e8/.github/workflows/ci.yml#L53

```yaml
  tests:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest]  
    name: tests
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - run: |
          go get -u github.com/mfridman/tparse
          go test -v -race -cover -json ./... | $(go env GOPATH)/bin/tparse -all
```
